### ISSUE TITLE
Wallet crashes on startup after receiving invalid txs with fake txout values

### ISSUE THREAD

**Issue by petertodd** [bitcoin-wallet/bitcoin-wallet#299]
See https://twitter.com/petertoddbtc/status/695506625419833344

**Comment by schildbach** [comment]
Can you send the crash report that is offered to be sent by the app on next startup? Also can you provide details about the transaction you created?

**Comment by petertodd** [comment]
Just tried it again now, and it started up fine, w/o giving an option to send a crash report.

The txs were created using this branch: https://github.com/petertodd/bitcoin/tree/2016-02-lie-to-spv

Basically the nValue fields in the txouts are all fake, and extremely large.

**Comment by schildbach** [comment]
Then can you send the logs through the app, and in the generated email note approx at what time the app crashed? I'll be able to read the exception from the log.

It's Options > Settings > Diagnostics > Report issue.

**Comment by schildbach** [comment]
Thanks for sending the log. This is the exception trace of the crash:

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309) ~[na:0.0]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354) ~[na:0.0]
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:242) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
Caused by: java.lang.IllegalArgumentException: 2100000000030000 satoshis exceeds maximum possible quantity of Bitcoin.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[na:0.0]
	at org.bitcoinj.core.Coin.<init>(Coin.java:87) ~[na:0.0]
	at org.bitcoinj.core.Coin.add(Coin.java:139) ~[na:0.0]
	at org.bitcoinj.core.Wallet.getBalance(Wallet.java:3070) ~[na:0.0]
	at de.schildbach.wallet.ui.WalletBalanceLoader.loadInBackground(WalletBalanceLoader.java:90) ~[na:0.0]
	at de.schildbach.wallet.ui.WalletBalanceLoader.loadInBackground(WalletBalanceLoader.java:41) ~[na:0.0]
	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312) ~[na:0.0]
	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69) ~[na:0.0]
	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66) ~[na:0.0]
	at android.os.AsyncTask$2.call(AsyncTask.java:295) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
	... 3 common frames omitted
```

**Comment by schildbach** [comment]
I believe this PR will fix the crash: https://github.com/bitcoinj/bitcoinj/pull/1178

Btw. I see you recovered by double spending your previous fake txns a couple of times. Did you notice any irregularities after the recovery? This code path is tested only rarely, so any confirmations welcome (-:

**Comment by joshafest** [comment]
Is this issue fixed?

**Comment by schildbach** [comment]
I believe I fixed it via https://github.com/bitcoinj/bitcoinj/commit/44ca39bfd7df0068a7aedb1780a8ad954e1cd50c.
