### ISSUE TITLE
Received Ping before version handshake is complete

### ISSUE THREAD

**Issue by Artieza** [bitcoin-wallet/bitcoin-wallet#378]
```
org.bitcoinj.core.ProtocolException: Received Ping before version handshake is complete.
	at org.bitcoinj.core.Peer.processMessage(Peer.java:478)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:182)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by schildbach** [comment]
That's a bug in Bitcoin Core. It sometimes sends a ping before the version handshake is complete.

**Comment by mrosseel** [comment]
also had this error when the full node was in pruned mode, preceded by the message: Peer does not have a copy of the block chain.
