### ISSUE TITLE
Need to update README.recover to help users with a PIN

### ISSUE THREAD

**Issue by jonathancross** [bitcoin-wallet/bitcoin-wallet#390]
Following directions in [README.recover](/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover), if I try to `send` from a wallet that had a PIN number, I get this error:

```
Exception in thread "main" org.bitcoinj.core.ECKey$KeyIsEncryptedException
	at org.bitcoinj.wallet.DecryptingKeyBag.maybeDecrypt(DecryptingKeyBag.java:49)
	at org.bitcoinj.wallet.DecryptingKeyBag.findKeyFromPubHash(DecryptingKeyBag.java:67)
	at org.bitcoinj.core.TransactionOutPoint.getConnectedRedeemData(TransactionOutPoint.java:169)
	at org.bitcoinj.core.TransactionInput.getConnectedRedeemData(TransactionInput.java:293)
	at org.bitcoinj.wallet.Wallet.signTransaction(Wallet.java:4066)
	at org.bitcoinj.wallet.Wallet.completeTx(Wallet.java:4003)
	at org.bitcoinj.tools.WalletTool.send(WalletTool.java:613)
	at org.bitcoinj.tools.WalletTool.main(WalletTool.java:372)
```

We should help users to understand that this means they need to supply the `--password=<PIN>` argument.

I already submitted a separate PR on that file (#389) and would be happy to add something about this cryptic error if you agree?

**Comment by schildbach** [comment]
Agreed.

**Comment by sni10** [comment]
Nothing works. All items work except the last one. I tried all the addresses that I could. I do not need to send anything. I just need to get a private key. And I get an error.

Pin code I specify the correct 100%

Exception in thread "main" org.bitcoinj.wallet.Wallet$CouldNotAdjustDownwards
        at org.bitcoinj.wallet.Wallet.completeTx(Wallet.java:3989)
        at org.bitcoinj.tools.WalletTool.send(WalletTool.java:613)
        at org.bitcoinj.tools.WalletTool.main(WalletTool.java:372)

I just need to remove the key, and nothing more. I could import it into the Bitcoin Core.

**Comment by jonathancross** [comment]
@sni10 What does this comment mean?
> "Nothing works. All items work except the last one."

**Comment by haplo** [comment]
I'm adding some documentation in #450 about how to dump private keys. One important step is to decrypt the wallet with the spending PIN, otherwise the private keys won't show.

**Comment by leagithub** [comment]
http://1501115629.theunitynetwork.com/register
