### ISSUE TITLE
Crash on Pause RequestCoinsActivity with open QR popup

### ISSUE THREAD

**Issue by lvaccaro** [bitcoin-wallet/bitcoin-wallet#447]
1. Go in RequestCoinsActivity
2. Click over the QR and open the QR popup.
3. Click the Home button to pause the activity.
4. Crash:
```
FATAL EXCEPTION: main
                                                                          Process: com.eternitywall.regtest, PID: 20911
                                                                          java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1386884 bytes
                                                                              at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3752)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by schildbach** [comment]
Thanks a lot for this report! I'm able to reproduce it.

**Comment by HashEngineering** [comment]
I reproduced this as well.  Could it be related to the bitmap of the QR
Code being saved?

**Comment by schildbach** [comment]
v5.37 should resolve the problem. Commits  825aa4389a72e0125bf41825856559d1a6941237 and 847ac1a12fcca5a6960796203263ba1115eea073 reduce memory usage of the bitmap by a huge amount.

**Comment by HashEngineering** [comment]
WalletAddressDialogFragment - This class doesn't result in a crash.  Bundle data is only the Address object and a label.
BitmapFragment - This class results in a crash - the bitmap is 1.8 MB.  The bundle data is the Bitmap.
