### ISSUE TITLE
I am getting the error, whenever i want to run application on a local device (Mobile Phone).

### ISSUE THREAD

**Issue by meshileya** [bitcoin-wallet/bitcoin-wallet#527]
```

03-23 04:21:49.912 4665-4665/com.developer.techies.thewallet W/CrashReporter: [main] crashing because of uncaught exception
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.developer.techies.thewallet/de.schildbach.wallet.ui.WalletActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0000
                                                                              	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2560) ~[na:0.0]
                                                                              	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640) ~[na:0.0]
                                                                              	at android.app.ActivityThread.access$800(ActivityThread.java:182) ~[na:0.0]
                                                                              	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) ~[na:0.0]
                                                                              	at android.os.Handler.dispatchMessage(Handler.java:111) ~[na:0.0]
                                                                              	at android.os.Looper.loop(Looper.java:194) ~[na:0.0]
                                                                              	at android.app.ActivityThread.main(ActivityThread.java:5682) ~[na:0.0]
                                                                              	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
                                                                              	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
                                                                              	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) ~[na:0.0]
                                                                              	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) ~[na:0.0]
                                                                              Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0000
                                                                              	at android.content.res.Resources.getValue(Resources.java:1516) ~[na:0.0]
                                                                              	at android.content.res.Resources.getDrawable(Resources.java:957) ~[na:0.0]
                                                                              	at android.content.Context.getDrawable(Context.java:408) ~[na:0.0]
                                                                              	at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:321) ~[na:0.0]
                                                                              	at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:741) ~[na:0.0]
                                                                              	at com.android.internal.policy.impl.PhoneWindow.setDefaultIcon(PhoneWindow.java:1729) ~[na:0.0]
                                                                              	at android.app.Activity.initWindowDecorActionBar(Activity.java:2182) ~[na:0.0]
                                                                              	at android.app.Activity.setContentView(Activity.java:2197) ~[na:0.0]
                                                                              	at de.schildbach.wallet.ui.WalletActivity.onCreate(WalletActivity.java:111) ~[na:0.0]
                                                                              	at android.app.Activity.performCreate(Activity.java:6161) ~[na:0.0]
                                                                              	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) ~[na:0.0]
                                                                              	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2507) ~[na:0.0]
                                                                              	... 10 common frames omitted
03-23 04:21:49.917 4665-4665/com.developer.techies.thewallet E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.developer.techies.thewallet, PID: 4665
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.developer.techies.thewallet/de.schildbach.wallet.ui.WalletActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0000
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2560)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:182)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5682)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
                                                                                Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0000
                                                                                   at android.content.res.Resources.getValue(Resources.java:1516)
                                                                                   at android.content.res.Resources.getDrawable(Resources.java:957)
                                                                                   at android.content.Context.getDrawable(Context.java:408)
                                                                                   at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:321)
                                                                                   at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:741)
                                                                                   at com.android.internal.policy.impl.PhoneWindow.setDefaultIcon(PhoneWindow.java:1729)
                                                                                   at android.app.Activity.initWindowDecorActionBar(Activity.java:2182)
                                                                                   at android.app.Activity.setContentView(Activity.java:2197)
                                                                                   at de.schildbach.wallet.ui.WalletActivity.onCreate(WalletActivity.java:111)
                                                                                   at android.app.Activity.performCreate(Activity.java:6161)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2507)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:182) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                   at android.os.Looper.loop(Looper.java:194) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5682) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
```

**Comment by schildbach** [comment]
I suspect this is on a fork of the app?

**Comment by HashEngineering** [comment]
Yes, this must be a fork where the package Id was changed and other changes resulted in a missing resource at runtime.  It won’t be too hard to figure out what resource 0x7f0c0000 is and then determine how to fix it.  This is probably outside the scope of Bitcoin Wallet.

**Comment by meshileya** [comment]
Alright, thanks. Will check it out.
