### ISSUE TITLE
Bitcoin wallet doesn't fetch exchange rates 

### ISSUE THREAD

**Issue by hedgecrog** [bitcoin-wallet/bitcoin-wallet#613]
The bitcoin wallet android app since at least a day ago doesn't fetch any exchange rates and therefore doesn't show the bitcoin balance in any real fiat currencies.

I've deleted the app and reinstalled from Play Store, and thereafter also tried the beta version to no success.

**Comment by HashEngineering** [comment]
The site used for exchange rates, BitcoinAverage.com, ceased being free in the past 12 hours based on what I could tell.  That service now requires a plan to use.

**Comment by schildbach** [comment]
I sent them an email and will report their answer.

**Comment by HashEngineering** [comment]
Here is my correspondence with them in a few days ago with chat feature on their website:

> The api without a key works.  I am wondering what are the limits.  Recently, I saw that prices had increased on the plans, which have limits.  What are the limits if we are not using a plan?

The answer was this:

> don’t count on the api working without a key, that will be closed very soon.
> So 0 requests without api key

I work on two forks of this wallet app that support other crypto-currencies.  On one we had set up a system of 4 methods of getting the bitcoin price.  The app would attempt to get the prices from two services that both query bitcoinaverage.com.  If these failed, then the app would try bitcoinaverage.com directly and lastly it would try btcpay.com.  For now this system is still working, since atleast 1 of the sources is still getting usable data.

On the second app, I was using bitcoinaverage.com and coingecko.com.  Coingecko doesn't provide as many currencies.  Coingecko only provides 46 of what BitcoinAverage.com offered while another service CryptoCompare.com has 115 of the same currencies.

I will be looking forward to the solution that Bitcoin Wallet ends up with.

**Comment by tmlee** [comment]
Hey co-founder of CoinGecko here, just wanted to understand what are the list of currencies that you all are looking for?

We may be able to support more exchange rate currency for BTC but it would only be for current price. No support for historical yet

**Comment by schildbach** [comment]
@HashEngineering Yesterday, I implemented support for CoinGecko via eb31280aa3b2cc5456324bf9ddc4821aabd1e821.

@tmlee The most problematic issue with CoinGecko is that lots of API requests are blocked by CloudFlare.

**Comment by tmlee** [comment]
@schildbach is this API requests coming from a single IP or multiple different IPs spread all over (coming from client device or from a server) ?

If you could provide the `Ray ID` in the error page, that can help us to troubleshoot the problem too

**Comment by schildbach** [comment]
@tmlee The requests are coming from the client devices. (Bitcoin Wallet is decentralized.)

I'll look for those Ray-IDs and post some. Thanks!

**Comment by schildbach** [comment]
> I sent them an email and will report their answer.

Indeed I got the answer that a plan is now required and there are no free options for free software projects any more.

**Comment by schildbach** [comment]
@tmlee Here is an example response I just got from your API:

```
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script><!--<![endif]-->




</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> api.coingecko.com</h2>
      </div><!-- /.header -->
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form" id="challenge-form" action="/api/v3/exchange_rates?__cf_chl_captcha_tk__=edabec407ee0b6154cc5ce0086a8877d61cd2ea0-1580915780-0-AdbWbPvi1VQfVP1jgGW7a-BicgbGiDFHf-bzqp_8Y2XM1y2DvgaDgVeksp0zpriI8-fgo0VpbwotCfMYBkaNgKOsLo-nHg2Tn4YFB6XA4Okmu92TGOMmfDjDt7gamzAR9dC36eMXZbWAJsA3EmPbHK2hekXo0VkNwoN4geOSd9qfVefMbLFIWOGZyWA9HOCQLRkk-bOxYtsWX_ciK3LKNwzRG-EBYIzJX1OcewHXYq1isUitaQO-SVHMAZr5u9L__qAqxsxSMpcTcc87s9OYI9csy1vMShFs6VhvfCU7AFA-dbxjNizia9vY24d3ulxZ5El4FD-etoGtj-NoHhElTVFjeJmXd5ywrpiI8j41edSs" method="POST" enctype="application/x-www-form-urlencoded">
  <input type="hidden" name="r" value="9eb083f643ef3414f84941ac21299746251b0563-1580915780-0-Aa+J3ZA2glVJPzdXCYqmLNO1N0iehHbGV4DDSKlzSL9/4PMCax9cSG6olDkirkUc2H59L6juuvxFbpc4CVBqIWucdWfVuWRnFHqE0YqMZ1t1LGpVMRTNVMSl+DrM8b4B81KYeqkTmuokgKHXhpUGzARixMnBYEDwYip4/yCg0GAN/rF23yPWQbnsOSBXqWyRmz8c2Jabb+CodjRqReKotCtnC7zTThs8He86+/0xPfmmfI454cgSudwA2mScD3FW8LL2hTvpLoac/Gg+QSYqXaNPgAJr3kEgdXYFk9hmjO3CYP7k2Wys0WIeP8qoitlKemeVGdnVzegvJ2ylRHyFMXvJx+Lx5qY382ykZJe6d7/paHumojZqr7pdzCKpAAHrEYO0KjvuZrxjQFDeBPMm9b0ANvRLEan7eKq0BnfRt05VsULGXfl+UzDkCN/rZAHeiqIxrP89wXGf6oliSeMbKkK0BH6TO5JC+6BosXkoG2kAvnW/JLlFIwP+9xK2gVOBXfM45N5YHweoihHiYsGVpz7IsdpuKF/1psg0mTGb8KQCLB8/cHH/LHWLB0zaLKZEb9Ip8cJef9u2RmnmhWCcClL8LpfomVqmGMUlaFvDaUdZTm65kPbIO32kTaPTiY2KVGaIS0A1HC+4ibkFDlF2smM0Re/jEKjVp/5lR1pB0G97nncWKUV7J0CXw3WjYUlYMM8oHOZeyTszQscoKQ0VzlZz5l73IZtC34OQq76mS7orzDKFEUqtsQgx0Qv6pi87rofEBSaPNW8/t+20Xi+YkGvlWDahrChqhHvrtx7F1U+2AfaG/dw8Dd1EOOgTC1H2BiQOo7y6iX6aO8smD+obUY1+LBa4rjvd6kwNet4KydTLZIVj1a1/Gmksfk3KeK0YT1l5feSJHMq1ytzJLAF0xXKqLfG7Fma0rlnntqxp0nzt">
  <script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal"  data-ray="5605d84a2f3658b9" async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>
  <div class="g-recaptcha"></div>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
…
```

**Comment by Xbjb8rVZ7ZJquS96Y4AJtNE4Pe9eNY1QGv** [comment]
> The bitcoin wallet android app since at least a day ago doesn't fetch any exchange rates and therefore doesn't show the bitcoin balance in any real fiat currencies.
> 
> I've deleted the app and reinstalled from Play Store, and thereafter also tried the beta version to no success.

**Comment by DarkAnge1** [comment]
Same issue here. Logcat tells this:
```
08-23 18:32:42.444 12491 12523 W CrashReporter: java.io.FileNotFoundException: /data/user/0/de.schildbach.wallet/cache/crash.trace: open failed: ENOENT (No such file or directory)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at libcore.io.IoBridge.open(IoBridge.java:574)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at de.schildbach.wallet.util.CrashReporter$ExceptionHandler.saveCrashTrace(CrashReporter.java:140)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at de.schildbach.wallet.util.CrashReporter$ExceptionHandler.uncaughtException(CrashReporter.java:128)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
08-23 18:32:42.444 12491 12523 W CrashReporter: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at libcore.io.Linux.open(Native Method)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8387)
08-23 18:32:42.444 12491 12523 W CrashReporter:         at libcore.io.IoBridge.open(IoBridge.java:560)
08-23 18:32:42.444 12491 12523 W CrashReporter:         ... 7 common frames omitted
08-23 18:32:42.444 12491 12516 W ContextImpl: Failed to ensure /data/user/0/de.schildbach.wallet/databases: mkdir failed: ENOENT (No such file or directory)
08-23 18:32:42.444 12491 12516 E SQLiteLog: (14) cannot open file at line 43466 of [831d0fb283]
08-23 18:32:42.444 12491 12516 E SQLiteLog: (14) os_unix.c:43466: (2) open(/data/data/de.schildbach.wallet/databases/exchange_rates) -
08-23 18:32:42.444 12491 12537 I DeterministicKeyChain: [AsyncTask #2] Took 1.065 ms
08-23 18:32:42.446 12491 12516 E SQLiteDatabase: Failed to open database '/data/user/0/de.schildbach.wallet/databases/exchange_rates'.
08-23 18:32:42.446 12491 12516 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/de.schildbach.wallet/databases/exchange_rates' with flags 0x30000000: Directory /data/user/0/de.schildbach.wallet/databases doesn't exist
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:270)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:213)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:535)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:222)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:214)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1158)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1138)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1002)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:991)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:232)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:177)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at androidx.room.RoomDatabase.inTransaction(RoomDatabase.kt:632)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.kt:451)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at de.schildbach.wallet.exchangerate.ExchangeRateDao_Impl.insertOrUpdate(ExchangeRateDao_Impl.java:63)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at de.schildbach.wallet.exchangerate.ExchangeRatesRepository$1.onResponse(ExchangeRatesRepository.java:109)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at java.lang.Thread.run(Thread.java:1012)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase: Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:232)
08-23 18:32:42.446 12491 12516 E SQLiteDatabase:        ... 23 more
08-23 18:32:42.449  1787 12540 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
08-23 18:32:42.452  1787  4552 W ActivityTaskManager:   Force finishing activity de.schildbach.wallet/.WalletActivity
```

**Comment by schildbach** [comment]
@DarkAnge1 Yours in an unrelated issue. What device are you using, what version of Android, and which version of the app?

**Comment by DarkAnge1** [comment]
@schildbach Somehow haven't got notification about response. I use latest available in Play Store app 10.15 and Android 14.

Wanted to provide you more details because there was message previously about inability to contact Exchange API, and wanted to also check on does the SQLite file exists or not and got different log output:
```
2024-08-29 10:12:38.705 18022-18022 ingecko.com/...         de.schildbach.wallet                 W  type=1400 audit(0.0:10652): avc:  denied  { write } for  name="exchange_rates" dev="sda16" ino=4800536 scontext=u:r:untrusted_app:s0:c50,c258,c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0 app=de.schildbach.wallet
2024-08-29 10:12:38.707 18022-18046 SQLiteLog               de.schildbach.wallet                 E  (14) cannot open file at line 43466 of [831d0fb283]
2024-08-29 10:12:38.707 18022-18046 SQLiteLog               de.schildbach.wallet                 E  (14) os_unix.c:43466: (13) open(/data/data/de.schildbach.wallet/databases/exchange_rates) - 
2024-08-29 10:12:38.705 18022-18022 ingecko.com/...         de.schildbach.wallet                 W  type=1400 audit(0.0:10653): avc:  denied  { open } for  path="/data/data/de.schildbach.wallet/databases/exchange_rates" dev="sda16" ino=4800536 scontext=u:r:untrusted_app:s0:c50,c258,c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0 app=de.schildbach.wallet
2024-08-29 10:12:38.708 18022-18046 SQLiteDatabase          de.schildbach.wallet                 E  Failed to open database '/data/user/0/de.schildbach.wallet/databases/exchange_rates'.
                                                                                                    android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/de.schildbach.wallet/databases/exchange_rates' with flags 0x30000000: Unable to deduct failure reason
....
```

Seems like SELinux misbehaves, but not sure how can I prevent this.

**Comment by schildbach** [comment]
I have scanned through the exceptions on the Play Store console, but could not find this error at all. So I assume it's extremely rare, possibly only affecting your device.

It can't create the file `/data/user/0/de.schildbach.wallet/cache/crash.trace` with error `open failed: ENOENT (No such file or directory)` but the thing is the directory is obtained via `Context.getCacheDir()` which is [guaranteed to exist and to be writable](https://developer.android.com/reference/android/content/Context#getCacheDir()). I could only imagine your device is out of storage, but you would know and the error would have a different text.

The other error `Cannot open database '/data/user/0/de.schildbach.wallet/databases/exchange_rates' with flags 0x30000000: Directory /data/user/0/de.schildbach.wallet/databases doesn't exist` is very similar. The API call is responsible for creating the directory if it doesn't exist.

I'm afraid I'd need your device for further analysis, and probably the first thing I'd try is a factory reset.

**Comment by schildbach** [comment]
@DarkAnge1 What brand and model number is your device?

**Comment by DarkAnge1** [comment]
It's an Essential Phone 1 with LineageOS 21 (Android 14) and relatively recent updates to it. Device is rooted. Has GAPS installed. 

Before responding to your message I've tried few things though to double check:
1)
- Removed the app with data
- Installed app from Play Store 
- Started it fresh on the phone
- It works

No issues observed, including exchange rates. Which is surpising, because I did the same multiple times prior to writing here.

2) 
- I recover data from the backup
- Application doesn' work (Caused by: java.io.FileNotFoundException: /data/user/0/de.schildbach.wallet/files/key-backup-protobuf: open failed: EACCES (Permission denied))
- User is set correctly for the files in /data/user/0/de.schildbach.wallet/ and directory itself

3)
- I remove application with data again. 
- I install application from the Play Store.
- It doesn't work (Directory /data/user/0/de.schildbach.wallet/databases doesn't exist)
- Seems like that is the behavior I've observed initially

4)
- I remove application AGAIN. No data this time anyway.
- I install application again from the Play Store.
- It works.

5)
Then I recover the backup data. Application crashes. (Caused by: java.io.FileNotFoundException: /data/user/0/de.schildbach.wallet/files/key-backup-protobuf: open failed: EACCES (Permission denied))

User is set correctly on recovery (I use Swift Backup).

I did the same (install from Play Store, recover from backup) on the AVD emulator (Android 14, also rooted) - and it worked without issues, wallet from backup opened and network got synced.

Seems like somehow very specific problem to me or the phone, so feel free to close the issue. I will just start with a new wallet. However, should you want to investigate - I'm ready to run any kind of test to help to pin it down.

Wanted to thank you for the app! I think it's a great and yet simple piece of software in my pocket.

**Comment by schildbach** [comment]
Have you reported this to Essential or LineageOS?

**Comment by DarkAnge1** [comment]
Reporting to Essential doesn't make any sense - company is dead. I thought about reporting to LineageOS, looked through reported bugs and haven't found anything even close to my issue. Considering complexity of the issue: app data restored from backup and only then it doesn't work it's hard to say if it's issue with Lineage or Swiftbackup. I do not have such issue with other apps, even restored from backups, so I believe it would be really hard to track, I will waste a lot of time of talented people with little to no benefit investigating this. I've already wasted your time.

It was more worrying, when fresh app didn't work, but then after investigating in this thread it was just a matter of 2 reinstalls.

Also I've found a workaround: after install and recovery on AVD device, I've made backup there and restored it on the phone. It works now. So, perhaps, it was a matter of backup, since it was taken on different device and different version of Android (10).

I hope this will help someone.
