### ISSUE TITLE
Recovering Bitcoins - password correct, during wallet-tool reset process shows error!

### ISSUE THREAD

**Issue by smile2more** [bitcoin-wallet/bitcoin-wallet#666]
Hi,

 I saw "#" during DECRYPTING. so my password was correct.

 Now, I am trying to reset and sync, but

 I am seeing this error:

root@kali:/home/kali/Downloads/bitcoinj/tools# ./wallet-tool reset --wallet=/tmp/decrypted-backup2
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.gradle.internal.reflect.JavaMethod (file:/usr/share/gradle/lib/gradle-base-services-4.4.1.jar) to class java.lang.ClassLoader
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Skipping wallettemplate: Gradle 4.4.1 and Java 11
Failed to load wallet '/tmp/decrypted-backup2': Could not parse input stream to protobuf
org.bitcoinj.wallet.UnreadableWalletException: Could not parse input stream to protobuf
        at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:448)
        at org.bitcoinj.tools.WalletTool.main(WalletTool.java:366)
Caused by: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
        at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:551)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:514)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:633)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:295)
        at com.google.protobuf.CodedInputStream$StreamDecoder.readGroup(CodedInputStream.java:2369)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:541)
        at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:293)
        at org.bitcoinj.wallet.Protos$Wallet.<init>(Protos.java:16928)
        at org.bitcoinj.wallet.Protos$Wallet.<init>(Protos.java:16771)
        at org.bitcoinj.wallet.Protos$Wallet$1.parsePartialFrom(Protos.java:20234)
        at org.bitcoinj.wallet.Protos$Wallet$1.parsePartialFrom(Protos.java:20228)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:96)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:329)
        at org.bitcoinj.wallet.Protos$Wallet.parseFrom(Protos.java:17888)
        at org.bitcoinj.wallet.WalletProtobufSerializer.parseToProto(WalletProtobufSerializer.java:622)
        at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:441)

 Please help. Thank you!

My private file was 2013 one.

**Comment by schildbach** [comment]
Is your decrypted backup human-readable? In this case, please follow this: https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md#recovering-from-base58-key-format

**Comment by nichole1892** [comment]
@smile2more 
were you able to recover your wallet, if you were not, contact me I can recover it for you
 : walletsrecoveryservice@gmail.com
