### ISSUE TITLE
java.lang.SecurityException: Need LOCAL_MAC_ADDRESS permission

### ISSUE THREAD

**Issue by pdrobek** [bitcoin-wallet/bitcoin-wallet#783]
What is going wrong with Bluetooth on Samsung?

```
I/Bluetooth: [main] Problem determining Bluetooth MAC via reflection
    java.lang.reflect.InvocationTargetException: null
        at java.lang.reflect.Method.invoke(Native Method)
        at de.schildbach.wallet.util.Bluetooth.getAddress(Bluetooth.java:66)
        at de.schildbach.wallet.WalletApplication.onCreate(WalletApplication.java:124)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7517)
        at android.app.ActivityThread.access$1400(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2150)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8577)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.SecurityException: Need LOCAL_MAC_ADDRESS permission: Neither user 10401 nor current process has android.permission.LOCAL_MAC_ADDRESS.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
        at android.os.Parcel.createException(Parcel.java:2369)
        at android.os.Parcel.readException(Parcel.java:2352)
        at android.os.Parcel.readException(Parcel.java:2294)
        at android.bluetooth.IBluetooth$Stub$Proxy.getAddress(IBluetooth.java:3613)
    	... 13 common frames omitted
```

**Comment by Rangssan** [comment]
Bitcoin Acout
bc1qgpz44lmsrhz5fmrq99y7ak6fjpjvfu3a57tq4j
Compete with acout

ในวันที่ พ. 29 ธ.ค. 2021 18:01 Paweł Drobek ***@***.***>
เขียนว่า:

**Comment by Rangssan** [comment]
Compete bitcoin Acout bc1qgpz44lmsrhz5fmrq99y7ak6fjpjvfu3a57tq4j

**Comment by Rangssan** [comment]
[]()[]()![Screenshot_20211230-034921_Trust Wallet.jpg](https://user-images.githubusercontent.com/95187627/147702318-bf603e84-7603-4d01-815b-37a583c1b3a1.jpg)

**Comment by schildbach** [comment]
That's normal, and it should not affect normal operation. Android has restricted access to the Bluetooth MAC, but the Bluetooth MAC is needed for the payment protocol.

You can put your Bluetooth MAC into the settings to work around that.

**Comment by SoheilAdmin** [comment]
bc1quc57lgsdhrxurmnp3hre07zfpx04jepdmcl65u

در تاریخ جمعه ۳۱ دسامبر ۲۰۲۱،‏ ۱۲:۱۵ Andreas Schildbach <
***@***.***> نوشت:

**Comment by pdrobek** [comment]
Ok got that, but is there any way to hack android behaviour and get MAC automatically?

**Comment by schildbach** [comment]
Any known "hacks" that can be used by an app are implemented in `Bluetooth.getAddress()`.

If you're talking about modifying Android itself, feel free to change `BluetoothAdapter.getAddress()` back to the original behaviour of returning the real MAC rather than just a fake one. Then the app will pick it up automatically.

**Comment by pdrobek** [comment]
thx :-)
